# Generated by Django 6.0.4 on 2026-04-13 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cryptocurrency_delete_userwatchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=255, verbose_name='ID Monety (CoinGecko)')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Obserwowana kryptowaluta',
                'verbose_name_plural': 'Obserwowane kryptowaluty',
                'unique_together': {('user', 'coin_id')},
            },
        ),
        migrations.DeleteModel(
            name='CryptoCurrency',
        ),
    ]
