"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv


load_dotenv()

# Konfiguracja UI Panela Admina (Unfold)
# settings.py

UNFOLD = {
    "SITE_TITLE": "CryptoPulse Admin",
    "SITE_HEADER": "CryptoPulse",
    "SITE_URL": "https://cryptopulseapp.vercel.app",
    "SITE_SYMBOL": "currency_bitcoin",
    "STRINGS": {
        "welcome_back": "Witaj ponownie w",
    },
    "COLORS": {
        "primary": {
            "50": "235 251 255",
            "100": "204 245 255",
            "200": "153 234 255",
            "300": "77 221 255",
            "400": "26 211 255",
            "500": "0 212 255",
            "600": "0 170 204",
            "700": "0 127 153",
            "800": "0 85 102",
            "900": "0 42 51",
            "950": "0 21 26",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Zarządzanie Systemem",
                "items": [
                    {
                        "title": "Użytkownicy",
                        "link": "/admin/auth/user/",
                        "icon": "person",
                    },
                    {
                        "title": "Tokeny API",
                        "link": "/admin/authtoken/tokenproxy/",
                        "icon": "vpn_key",
                    },
                ],
            },
            {
                "title": "Giełda i Portfel",
                "items": [
                    {
                        "title": "Obserwowane",
                        "link": "/admin/api/userwatchlist/",
                        "icon": "star",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "auth.user",
                "api.userwatchlist",
            ],
            "items": [
                {
                    "title": "Podgląd",
                    "link": "admin:index",
                },
            ],
        },
    ],
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-e89x^fx2v=b83xoo$fm@^^vy_b6j4$25!^2-@1s8%f#5nyvr!8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'crypto-pulse-web-app.onrender.com',
    'localhost',
    '127.0.0.1'
]

# Pobranie adresu przypisanego automatycznie przez usługę Render
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    # Panel administracyjny (Unfold musi być przed django.contrib.admin)
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # pobrane biblioteki
    'rest_framework',
    'corsheaders',
    'drf_spectacular',

    # Aplikacja
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- Custom App Settings ---

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = True # Pozwalamy frontendowi na dowolnym porcie/domenie się łączyć

# Django REST Framework & Spectacular Configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Crypto Pulse Proxy API',
    'DESCRIPTION': 'API Proxy for CoinGecko with caching and 429 error handling',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = BASE_DIR / 'staticfiles'


